version: '{build}'
clone_depth: 10
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      HOST: x86_64-unknown-linux-gnu
      TARGET: wasm32-unknown-unknown
      MODE: release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      HOST: x86_64-pc-windows-gnu
      TARGET: x86_64-pc-windows-gnu
      BIN_NAME: slime99
      ARCHIVE_NAME: slime99-windows-x86_64
      MODE: release
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      HOST: x86_64-unknown-linux-gnu
      TARGET: x86_64-unknown-linux-gnu
      MODE: release
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
      HOST: x86_64-apple-darwin
      TARGET: x86_64-apple-darwin
      MODE: release

for:
  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          TARGET: x86_64-pc-windows-gnu
    install:
      - cmd: >-
          appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe

          rustup-init -yv --default-toolchain stable --default-host %HOST%

          set PATH=%PATH%;%USERPROFILE%\.cargo\bin

          rustc -V

          cargo -V

          set PATH=%PATH%;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

          g++ --version

    build_script:
      - cmd: >-
          echo on

          if "%MODE%" == "release" ( set RELEASE_FLAG=--release& set TARGET_DIR=release& set NAME_SUFFIX=) else ( set RELEASE_FLAG=& set TARGET_DIR=debug& set NAME_SUFFIX=-debug)

          set FULL_NAME=%ARCHIVE_NAME%%NAME_SUFFIX%-%APPVEYOR_REPO_BRANCH%

          mkdir tmp

          mkdir tmp\%FULL_NAME%

          copy extras\windows\* tmp\%FULL_NAME%

          cargo build %RELEASE_FLAG% --manifest-path=graphical/Cargo.toml

          echo copy target\%TARGET_DIR%\slime99_graphical.exe tmp\%FULL_NAME%\%BIN_NAME%.exe

          copy target\%TARGET_DIR%\slime99_graphical.exe tmp\%FULL_NAME%\%BIN_NAME%.exe

          cargo build %RELEASE_FLAG% --manifest-path=graphical/Cargo.toml --no-default-features --features=prototty_graphical_gfx

          copy target\%TARGET_DIR%\slime99_graphical.exe tmp\%FULL_NAME%\%BIN_NAME%-opengl.exe

          powershell.exe -nologo -noprofile -command "& { Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::CreateFromDirectory('tmp', '%FULL_NAME%.zip'); }"

    artifacts:
    - path: '*.zip'
      name: files.gridbugs.org

    deploy:
    - provider: Environment
      name: files.gridbugs.org

  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          TARGET: x86_64-unknown-linux-gnu
    install:
      - sh: >-
          sudo apt-get install libasound2-dev

          curl -sSf https://sh.rustup.rs | sh -s -- --quiet --default-host $HOST --default-toolchain stable --profile minimal -y

          export PATH="$HOME/.cargo/bin:$PATH"

          rustc -V

          cargo -V

    build_script:
      - sh: >-
          if [ "$MODE" == "release" ]; then
            TARGET_DIR="release"
            RELEASE_FLAG="--release"
            NAME_SUFFIX=""
          else
            TARGET_DIR="debug"
            RELEASE_FLAG=""
            NAME_SUFFIX="-debug"
          fi

          cargo build $RELEASE_FLAG --manifest-path=graphical/Cargo.toml --no-default-features --features=prototty_graphical_gfx

          mv -v target/$TARGET_DIR/slime99_graphical{,_opengl}

          cargo build $RELEASE_FLAG --manifest-path=graphical/Cargo.toml

          cargo build $RELEASE_FLAG --manifest-path=ansi-terminal/Cargo.toml

          strip -v target/$TARGET_DIR/slime99_graphical_opengl

          strip -v target/$TARGET_DIR/slime99_graphical

          strip -v target/$TARGET_DIR/slime99_ansi_terminal

          MODE=$MODE ZIP_NAME=slime99-linux-x86_64$NAME_SUFFIX-$APPVEYOR_REPO_BRANCH scripts/make_zip_unix.sh

    artifacts:
    - path: '*.zip'
      name: files.gridbugs.org

    deploy:
    - provider: Environment
      name: files.gridbugs.org

  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          TARGET: wasm32-unknown-unknown
    install:
      - sh: >-
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash

          nvm use v12

          curl -sSf https://sh.rustup.rs | sh -s -- --quiet --default-host $HOST --default-toolchain stable --profile minimal -y

          export PATH="$HOME/.cargo/bin:$PATH"

          rustup target add $TARGET

          cargo install wasm-bindgen-cli --force --version 0.2.58 # this has to match the version in Cargo.lock

          rustc -V

          cargo -V

    build_script:
      - sh: >-
          pushd web

          npm install

          if [ "$MODE" == "release" ]; then
            BUILD_MODE=production
          else
            BUILD_MODE=development
          fi

          npm run build -- --mode $BUILD_MODE

          for f in dist/*.wasm; do mv -v $f ${f%.wasm}.wrong-mime.wasm; done

          mkdir slime99

          mv dist slime99/$APPVEYOR_REPO_BRANCH

          zip -r slime99.zip slime99

          popd

          mv web/slime99.zip .

    artifacts:
    - path: '*.zip'
      name: games.gridbugs.org

    deploy:
    - provider: Environment
      name: games.gridbugs.org

  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: macOS
          TARGET: x86_64-apple-darwin
    install:
      - sh: >-
          curl -sSf https://sh.rustup.rs | sh -s -- --quiet --default-host $HOST --default-toolchain stable --profile minimal -y

          export PATH="$HOME/.cargo/bin:$PATH"

          rustc -V

          cargo -V

    build_script:
      - sh: >-
          if [ "$MODE" == "release" ]; then
            TARGET_DIR="release"
            RELEASE_FLAG="--release"
            NAME_SUFFIX=""
          else
            TARGET_DIR="debug"
            RELEASE_FLAG=""
            NAME_SUFFIX="-debug"
          fi

          cargo build $RELEASE_FLAG --manifest-path=graphical/Cargo.toml --no-default-features --features=prototty_graphical_gfx

          mv -v target/$TARGET_DIR/slime99_graphical{,_opengl}

          cargo build $RELEASE_FLAG --manifest-path=graphical/Cargo.toml

          cargo build $RELEASE_FLAG --manifest-path=ansi-terminal/Cargo.toml

          strip -v target/$TARGET_DIR/slime99_graphical_opengl

          strip -v target/$TARGET_DIR/slime99_graphical

          strip -v target/$TARGET_DIR/slime99_ansi_terminal

          MODE=$MODE ZIP_NAME=slime99-macos-x86_64$NAME_SUFFIX-$APPVEYOR_REPO_BRANCH scripts/make_zip_unix.sh

          MODE=$MODE APP_NAME=Slime99 DMG_NAME=Slime99-$APPVEYOR_REPO_BRANCH.dmg scripts/make_dmg_macos.sh

    artifacts:
    - path: '*.zip'
      name: files.gridbugs.org
    - path: '*.dmg'
      name: files.gridbugs.org

    deploy:
    - provider: Environment
      name: files.gridbugs.org
