[package]
name = "rip_graphical"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[features]
default = ["prototty_graphical"]

[dependencies]
log = "0.4"
env_logger = "0.7"
prototty_graphical = { version = "0.28", optional = true }
prototty_graphical_gfx = { version = "0.28", optional = true }
rip_prototty = { path = "../prototty" }
rip_native = { path = "../native" }
